export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  REQUEST_TOKEN_REQUEST: "REQUEST_TOKEN_REQUEST",
  REQUEST_TOKEN_SUCCESS: "REQUEST_TOKEN_SUCCESS",
  REQUEST_TOKEN_FAILURE: "REQUEST_TOKEN_FAILURE",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
